language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: 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
  keep_history: true
  on:
    branch: main